package statuscodes;

public enum DownloadStatus {
    DOWNLOAD_REQUEST, DOWNLOAD_REQUEST_VALID, DOWNLOAD_REQUEST_INVALID, DOWNLOAD_REQUEST_FAIL, DOWNLOAD_START,
    DOWNLOAD_SUCCESS, DOWNLOAD_FAIL,
};
